### PR TITLE
Fix jedis leak

### LINKED ISSUE #38: `Client implements Closeable`?
That jedis pool looks like it could use a `close()`...

### PR DESCRIPTION
**Pull request by b4hand**
Fixes #38.

### CODE REVIEW

**Comment by b4hand** [comment]
I think there's at least one remaining issue due to the `Events` class creating and getting a `Jedis` instance on one thread and handing it to a separate thread for the `EventThread`. I'm going to address that separately.

**Comment by davidann** [comment]
I'm trying this out in my docker container.  I'll report on the results.

**Comment by dlecocq** [comment]
LGTM

**Comment by b4hand** [comment]
I'll go ahead and merge and work on the thread safety issue.

**Pull request merged**
